### ISSUE TITLE
Collapsible headers for each year

### ISSUE THREAD

**Issue by shalvah** [shalvah/oldtweets.today#30]
For someone with a lot of tweets, after results have been fetched, it takes a lot of scrolling to get to tweets from an older year (say 2013). It would be nice if the year headers could be clicked to hide/show the content as needed.

The task is to modify the header shown for each year so that:

- The header is clickable
- Clicking the header hides the view containing all the tweets in that year.
- Clicking the header again expands the view containing all the tweets in that year.

That is, an effect similar to Bootstrap's collapse https://getbootstrap.com/docs/4.3/components/collapse/

**Comment by MichaelGee** [comment]
I can fix it.

**Comment by Frontend-io** [comment]
Hi, I'm Jefferson, a frontend developer. 
I can make this. 
I have utilised it before building a CBT app interface. Questions are matched to their buttons, onclick the button, the question that matches the data attribute of the button is manipulated (shown, visible) and others are hidden or otherwise...

So...
